---
- name: "Hardening SELinux"
  hosts: all
  become: true
  become_method: sudo
  become_user: root
  ignore_errors: true

  pre_tasks:
    - name: install policycoreutils-python-utils
      package:
        name: policycoreutils-python-utils
        state: latest
      when: ansible_distribution == 'Fedora'

    - name: install policycoreutils-python
      package:
        name: policycoreutils-python
        state: latest
      when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

    - name: save configuration
      command: semanage -o ~/.defaultconf
      ignore_errors: yes

  vars_files:
    # booleans hardening
    - files/cant_connect.yml
    - files/deny_execmem.yml
    - files/deny_export.yml
    # disable modules
    - files/modules.yml
    # users mapping
    - users/user_mapping.yml

  vars:
    selinux_policy: targeted
    selinux_state: enforcing
    selinux_booleans: "{{ cant_connect + deny_execmem + deny_export }}"
    selinux_logins: "{{ user_mapping }}"
    selinux_modules: "{{ manage_modules }}"

  roles:
    - linux-system-roles.selinux
